package com.gmu.gateway.util;

import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.Map;

@Component
public class JwtUtil {

    /**
     * Main JWT secret Used for: - User access token - Internal service token
     */
    @Value("${jwt.secret}")
    private String secret;

    private SecretKey secretKey;

    /**
     * User access token expiry Example: 15 min
     */
    @Value("${jwt.access.expiration}")
    private long accessTokenExpiry;

    /**
     * Internal service token expiry Example: 5 min
     */
    @Value("${jwt.internal.expiration}")
    private long internalTokenExpiry;

    @PostConstruct
    public void init() {
        this.secretKey = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * ================================================== USER TOKEN Generated by  Auth Service ==================================================
     *
     * Claims Example:
     * { userId:1, role:ADMIN }
     */
    public String generateToken(String subject, Map<String, Object> claims) {
        return Jwts.builder()
                .subject(subject)
                .claims(claims)
                .issuedAt(new Date())
                .expiration(new Date(System.currentTimeMillis() + accessTokenExpiry))
                .signWith(secretKey)
                .compact();
    }

    /**
     * ================================================== INTERNAL TOKEN Generated
     * by: Gateway Lead Service AI Service etc
     * ==================================================
     *
     * Example:
     * { service:gateway, userId:10, role:COUNSELLOR }
     */
    public String generateInternalToken(Map<String, Object> claims) {
        return Jwts.builder()
                .claims(claims)
                .issuedAt(new Date())
                .expiration(new Date(System.currentTimeMillis() + internalTokenExpiry))
                .signWith(secretKey)
                .compact();
    }

    /**
     * Validate token
     */
    public Claims validateToken(String token) {
        try {
            return Jwts.parser()
                    .verifyWith(secretKey)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload();
        } catch (ExpiredJwtException ex) {
            throw new RuntimeException("Token expired");
        } catch (UnsupportedJwtException ex) {
            throw new RuntimeException("Unsupported token");
        } catch (MalformedJwtException ex) {
            throw new RuntimeException("Malformed token");
        } catch (SecurityException ex) {
            throw new RuntimeException("Invalid signature");
        } catch (IllegalArgumentException ex) {
            throw new RuntimeException("Empty token");
        }
    }

    /**
     * Extract user email
     */
    public String extractSubject(String token) {
        return validateToken(token).getSubject();
    }

    /**
     * Extract all claims
     */
    public Claims extractClaims(String token) {
        return validateToken(token);
    }

    /**
     * Extract user role
     */
    public String extractRole(String token) {
        return validateToken(token).get("role", String.class);
    }

    /**
     * Extract caller service
     * gateway lead-service ai-service
     */
    public String extractService(String token) {
        return validateToken(token).get("service", String.class);
    }

    /**
     * Expiry check
     */
    public boolean isTokenExpired(String token) {
        return validateToken(token)
                .getExpiration()
                .before(new Date());
    }
}