# =====================================
# JWT CONFIGURATION
# =====================================

jwt:
  # User JWT secret
  secret: qwertyuiopasfhjvsahjdsvfdvnjkndfkjvjdkfnvklnklfdvkjndfkjvnjkdnfjkvnkldfnvklndklfnvkldfnvklndklfnvdf
  # User access token
  access:
    expiration: 900000     # 15 min
  # Gateway internal token
  internal:
    expiration: 300000     # 5 min



security:
  publicEndpoints:
    - /api/leads/auth/login
    - /api/leads/auth/refresh
    - /api/leads/auth/logout
    - /api/leads/health/info

# =====================================
# GATEWAY ROUTING
# =====================================

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

        # ==========================
        # AUTH SERVICE
        # ==========================

            - id: auth-service

              uri: http://localhost:8081

              predicates:
                - Path=/api/auth/**



        # ==========================
        # LEAD SERVICE
        # ==========================

            - id: lead-service

              uri: http://192.168.1.13:8089      

              predicates:
                - Path=/api/leads/**
